# Generated by Django 2.2.16 on 2022-01-28 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220128_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Публикацию', 'verbose_name_plural': 'Публикации'},
        ),
    ]
